In [35]:
# evens = [2, 4, 0, 100, 4, 11, 2602, 36]

# # i = 0 #initialise counter
# # while i != len(evens):
# #     print(evens[i])
# #     i += 1

# #needs testing
# even=0
# while even in range(len(evens)):
#     print(even)

In [36]:
#remove doubles
ages = [15,13,16,18,19,15,10]
j = 0

for i in range(0, len(ages)):
    while j < len(ages):
        if ages[i] == ages[j]:
            ages.pop(j)
        j+=1
print(ages)


[13, 16, 18, 19, 15, 10]


In [37]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.65279032 0.63505887]
 [0.99529957 0.58185033]]


In [38]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array. n.b. the original array is still there
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
2
77


In [39]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [40]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [41]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [42]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [43]:
# Python Data Science Handbook pgs. 33-
import numpy as np

L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [45]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#integer array
print(np.array([1,4,2,5,3]))

#upcasted int array to float
print(np.array([3.14,4,2,3]))

#explicitly set data type of array
print(np.array([1,2,3,4], dtype='float32'))
print(np.array([1,2,3,4], dtype='int'))

#initialising a multidimensional array suing list of lists
#inner lists treated as rows of resulting 2D-array
print(np.array([range(i, i+3) for i in [2,4,6]]))


[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[1. 2. 3. 4.]
[1 2 3 4]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [47]:
#create a length-10 int array filled with zeros
print(np.zeros(10, dtype=int))

#create a 3x5 float array filled with ones
print(np.ones((3,5), dtype=float))

#create a 3x5 array filled with 3.14
print(np.full((3,5), 3.14))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [48]:
# create an array filled with a linear sequence starting at 0,
# ending at 20 and with steps of size 2
print(np.arange(0,20,2))

# create an array of five values evenly spaced between 0 and 1
print(np.linspace(0,1,5))

# create a 3x3 array of uniformly distributed random values
# between 0 and 1
print(np.random.random((3,3)))

# create a 3x3 array of normally distributed random values with
# mean 0 and standard deviation 1
print(np.random.normal(0,1,(3,3)))

[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.41436859 0.4746975  0.6235101 ]
 [0.33800761 0.67475232 0.31720174]
 [0.77834548 0.94957105 0.66252687]]
[[ 0.02686925  1.05583713 -0.07318342]
 [-0.66572066 -0.04411241 -0.36326702]
 [-0.01234481  0.04212149  1.95929589]]


In [49]:
# create a 3x3 array of random integers in the interval [0, 10)
print(np.random.randint(0,10,(3,3)))

# create a 3x3 identity matrix
print(np.eye(3))

# create an uninitialised array of three integers.
# the values will be whatever happens to already occupy that memory location
print(np.empty(3))

[[3 3 2]
 [3 4 1]
 [2 9 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [50]:
np.random.seed(0) # for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional array

print("x3 ndim (number of dimensions): ", x3.ndim)
print("x3 shape (size of each dimension): ", x3.shape)
print("x3 size (total size of array): ", x3.size)
print("x3 dtype (data type): ", x3.dtype)
print("x3 itemsize (size in bytes of each array element): ", x3.itemsize, "bytes")

# expectation: nbytes = itemsize * size
print("x3 nbytes (total size in bytes of the array): ", x3.nbytes, "bytes")


x3 ndim (number of dimensions):  3
x3 shape (size of each dimension):  (3, 4, 5)
x3 size (total size of array):  60
x3 dtype (data type):  int64
x3 itemsize (size in bytes of each array element):  8 bytes
x3 nbytes (total size in bytes of the array):  480 bytes


In [51]:
# accessing items in a multidimensional array
print(x2[0,0])

# modifying values in a multidimensional array
x2[0,0] = 12
print(x2[0,0])

# numpy arrays have a fixed type. Inserting e.g. a float into an integer
# array will truncate the float


3
12


In [56]:
# accessing subarrays with slices
# x[start:stop:step]
# default values: start=0, stop=size of dimension, step=1
x = np.arange(10)
print(x)

print(x[:5]) # first five elements

print(x[5:]) # elements after index 5

print(x[4:7]) # middle subarray

print(x[::2]) # every other element

print(x[1::2]) # every other element starting at index 1

print(x[::-1]) # all elements reversed

print(x[5::-2]) # reversed every other from index 5

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [58]:
# slices in multidimensional arrays
print(x2)

print(x2[:2, :3]) # first two rows, first three columns

print(x2[:3, ::2]) # all rows, every other column

# subarray dimensions reversed together
print(x2[::-1, ::-1])

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


In [59]:
# accessing array rows and columns
print(x2[:, 0]) # first column of x2

print(x2[0, :]) # first row of x2

print(x2[0]) # equivalent to x2[0, :]

[12  7  1]
[12  5  2  4]
[12  5  2  4]


In [60]:
# array slices return views rather than copies of array data.
# any modifications in the subarray (slice) will appear in the 
# original array
print(x2)

x2_sub = x2[:2, :2] # extract 2x2 subarray
print(x2_sub)

x2_sub[0, 0] = 99
print(x2_sub)

print(x2)

# only access the part we need from a large dataset without needing
# to copy the entire thing into buffer

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5]
 [ 7  6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [61]:
# creating a copy of the data within an array or subarray

x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0,0] = 42
print(x2_sub_copy)

print(x2)

[[99  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [63]:
# reshaping arrays

# place numbers 1 to 9 in a 3x3 grid
# n.b. size of initial array must match size of reshaped array
grid = np.arange(1,10).reshape((3,3))
print(grid)

# convert a one-dimensional array into a two-dimensional row or
# column matrix
x = np.array([1,2,3])

print(x.reshape((1,3))) # row vector via reshape

print(x[np.newaxis, :]) # row vector via newaxis

print(x.reshape((3,1))) # column vector vis reshape

print(x[:, np.newaxis]) # column vector via newaxis

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [67]:
# concatenation of arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y]))

# concatenate more than two arrays at once
z = [99,99,99]
print(np.concatenate([x, y, z]))

# concatenation for two-dimensional arrays
grid = np.array([[1,2,3],[4,5,6]])
# concatenate along the first axis
print(np.concatenate([grid, grid]))
# concatenate along the second axis (zero-indexed)
print(np.concatenate([grid, grid], axis=1))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [69]:
# concatenating mixed dimensional arrays
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

# vertically stack the arrays
print(np.vstack([x, grid]))

# horizontally stack the arrays
y = np.array([[99],[99]])
print(np.hstack([grid, y]))

# similarly, np.dstack will stack along the third axis

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


In [76]:
# splitting arrays
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5]) # splits before index 3 and index 5
                            # i.e. n plit points leads to n+1 subarrays
print(x1, x2, x3)

grid = np.arange(16).reshape((4,4))
print(grid)

upper, lower = np.vsplit(grid, [2]) # splits horizontally before 
                                    # row index 2
print(upper)
print(lower)

left, right = np.hsplit(grid, [2]) # splits vertically before column
                                    # index 2
print(left)
print(right)

# similarly, np.dsplit will split along the third axis

[1 2 3] [99 99] [3 2 1]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [77]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10,size=5)
print(compute_reciprocals(values))

big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

[0.16666667 1.         0.25       0.25       0.125     ]
1.33 s ± 9.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


page 51